[package]
name = "aobench"
version = "0.1.0"
edition = "2021"
authors = ["Will Usher <willusher.life@gmail.com>"]
build = "build.rs"

[dependencies]
image = "0.25"
rand = "0.8"
ispc = { path = "../../" }

[build-dependencies]
ispc = { path = "../../" }

